// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package msgs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionedValueProto struct {
	VersionBytes         []byte   `protobuf:"bytes,1,opt,name=version_bytes,json=versionBytes,proto3" json:"version_bytes,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionedValueProto) Reset()         { *m = VersionedValueProto{} }
func (m *VersionedValueProto) String() string { return proto.CompactTextString(m) }
func (*VersionedValueProto) ProtoMessage()    {}
func (*VersionedValueProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *VersionedValueProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedValueProto.Unmarshal(m, b)
}
func (m *VersionedValueProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedValueProto.Marshal(b, m, deterministic)
}
func (m *VersionedValueProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedValueProto.Merge(m, src)
}
func (m *VersionedValueProto) XXX_Size() int {
	return xxx_messageInfo_VersionedValueProto.Size(m)
}
func (m *VersionedValueProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedValueProto.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedValueProto proto.InternalMessageInfo

func (m *VersionedValueProto) GetVersionBytes() []byte {
	if m != nil {
		return m.VersionBytes
	}
	return nil
}

func (m *VersionedValueProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *VersionedValueProto) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionedValueProto)(nil), "msgs.VersionedValueProto")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xbb, 0x6e, 0x83, 0x40,
	0x10, 0x45, 0x45, 0x5e, 0x8a, 0x56, 0xd0, 0x90, 0x14, 0x28, 0x55, 0x94, 0x34, 0xa9, 0xd8, 0x22,
	0x7f, 0xc0, 0x17, 0x58, 0x96, 0x8c, 0x25, 0x37, 0xd6, 0x3e, 0xc6, 0x0b, 0x32, 0xcb, 0xa0, 0xd9,
	0x01, 0x99, 0xbf, 0xb7, 0x58, 0x90, 0xab, 0x99, 0x7b, 0x8e, 0x6e, 0x71, 0x45, 0x16, 0x18, 0x49,
	0x39, 0x28, 0x07, 0x42, 0xc6, 0xfc, 0xc5, 0x07, 0x17, 0x7e, 0x3a, 0xf1, 0x51, 0x03, 0x85, 0x16,
	0x7b, 0xb0, 0xb5, 0xea, 0x46, 0xd8, 0x45, 0xf9, 0x2b, 0xb2, 0x69, 0xc5, 0x67, 0x3d, 0x33, 0x84,
	0x22, 0xf9, 0x4e, 0xfe, 0xd2, 0x7d, 0xba, 0xc1, 0x6a, 0x61, 0xf9, 0xa7, 0x78, 0x9d, 0x96, 0x4a,
	0xf1, 0x14, 0xe5, 0x1a, 0xf2, 0x2f, 0xf1, 0xee, 0x81, 0x95, 0x55, 0xac, 0x8a, 0xe7, 0x28, 0x1e,
	0xb9, 0x3a, 0x9e, 0x0e, 0xae, 0xe5, 0x66, 0xd4, 0xa5, 0x41, 0x2f, 0x9b, 0x79, 0x00, 0xea, 0xc0,
	0x3a, 0x20, 0x79, 0x51, 0x9a, 0x5a, 0x23, 0x0d, 0x12, 0xc8, 0x0d, 0x5d, 0xa7, 0xed, 0xe1, 0x9b,
	0x77, 0x9e, 0x65, 0x60, 0xc5, 0x60, 0xf5, 0x7a, 0x0d, 0xf6, 0x06, 0xc9, 0x5a, 0x2d, 0x97, 0x19,
	0xfa, 0x2d, 0x6e, 0xfa, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0x29, 0x43, 0x57, 0x7a, 0xe4, 0x00,
	0x00, 0x00,
}
